### PR TITLE
feat: cross browser audit

### PR DESCRIPTION
**Pull request by tikagan**
## Description

- [x] updates font files to fix font weight irregularities in the headers + buttons
- [x] primary cta button polish, background color + glow slightly more opaque 
- [x] adds missing copy from accordion card "Effortless Deal Tracking"
- [x] removes focus ring on hover from github + slack ctas in subfooter card styling
- [x] changes secondary cta arrow to icon instead of unicode character
- [x] signup form country dropdown shows 7 fields, solid background color when open
- [x] signup form submit button doesn't show loading animation after successful form submit
- [x] primary cta on safari svg shape (on the left) renders as a smooth shape
- [x] in iOS safari primary cta is a rectangle not custom shape, fixes shape disappearing on iOS because of high paint requirements 
- [x] page data in state doesn't clear when navigating pages, fixes no footer rendering on signup page

Not addressed in this PR: 
- accordion animation jerky on safari 
- email data validation in forms

requested changes (noted in ticket + below): 
- [x] data storage units displayed as superscript
- [x] bullet points on accordion card left aligned with above text
- [x] fixes signup card height change when dropdown is opened
- [x] background images z-index reduced so they don't overlap site content

## Ticket link

Ticket [AU-2950](https://www.notion.so/agencyundone/AU-2590)

### CODE REVIEW

**Review by jfmerced — CHANGES_REQUESTED** [review]
Left comments about the CTA glow on mobile (when it's a rectangle) and the "view roadmap on github" CTA getting covered in Notion

**Comment by orvn** [comment]
@jfmerced feel free to give this a review if all the changes are satisfied, or if you're requesting changes.

**Comment by jfmerced** [comment]
- Still seeing the "view roadmap on github" CTA blocked off, testing on my own iPhone 11 with Safari, but I don't think that was addressed here yet

New change requested
- There are bullet points in the code section in the hero that should be removed

**Review by jfmerced — CHANGES_REQUESTED** [review]
- Still seeing the "view roadmap on github" CTA blocked off, testing on my own iPhone 11 with Safari, but I don't think that was addressed here yet

New change requested:
- There are bullet points in the code section in the hero that should be removed

**Review by jfmerced — APPROVED** [review]
Looks good

**Review by jfmerced — CHANGES_REQUESTED** [review]
All changes lgtm but found new issues with tab navigation on Safari and Firefox

Safari:
- skips entirety of the nav bar and only goes to the Features cards and subfooter email signup field
- rest of the buttons are skipped over

Firefox:
- skips all of nav except for features, how it works, and roadmap
- skips to features cards then subfooter email signup field
- goes to the footer logo but skips the rest of footer buttons

**Review by jfmerced — APPROVED** [review]
approving after troubleshooting tab nav on firefox

**Review by orvn — APPROVED** [review]

**Pull request merged**
