### PR TITLE
content: smaller background images

### PR DESCRIPTION
**Pull request by tikagan**
## Description

- [x] warped-torus background image optimized through tinyPNG
- [x] other background images converted to JPGs with dark background, kept at original dimension size (because smaller dimension size did not look good as a PNG)

### CODE REVIEW

**Comment by orvn** [comment]
This is still WIP yeah @tikagan?

**Comment by tikagan** [comment]
> This is still WIP yeah @tikagan?

@orvn yes until you and Emily look at the fleek link and approve how the images look (I put the link [in slack](https://agencyundone.slack.com/archives/C05KVU6KFSA/p1694716298269299) and tagged y'all)

**Review by orvn — CHANGES_REQUESTED** [review]
Looks mostly good! I think the one issue is this image:

`images/warped-torus-made-of-segments.png` at 426.13 kB

It's a good bit bigger than the other images, but it appears that that's because it still has transparency. @tikagan, can you have the creative team grab it with a black background? (and then resized and optimized)

**Review by orvn — APPROVED** [review]
Approving for now, we can address the other image later on, but want to get these optimized images in.

**Pull request merged**
